@BackEnd_HostAddress = http://localhost:5089
@BackEnd_Https = https://localhost:7065
@mitoken = ""

GET {{BackEnd_Https}}/api/admin/reportes/clientes
Accept: application/json
Authorization: Bearer {{mitoken}}
###

GET {{BackEnd_Https}}/api/admin/reportes/clientes/3
Accept: application/json
Authorization: Bearer {{mitoken}}

### 

GET {{BackEnd_HostAddress}}/api/categorias
Accept: application/json

###
GET {{BackEnd_HostAddress}}/api/estilos
Accept: application/json

###

GET {{BackEnd_HostAddress}}/api/categorias/1
Accept: application/json

###
GET {{BackEnd_HostAddress}}/api/estilos/1
Accept: application/json

###
POST {{BackEnd_HostAddress}}/api/auth/register-cliente
Content-Type: application/json
{
  "Email": "emaildeprueba@gmail.com",
  "NombreUsuario": "Prueba123",
  "Contrasena": "contrasenaDePrueba",
  "Nombres": "John John",
  "Apellidos": "Doe Doe",
  "TipoDocumento": "DNI",
  "Documento": "11111111"
}
###
POST {{BackEnd_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "UsuUsernameOrEmail": "emaildeprueba@gmail.com",
  "UsuContrasena": "contrasenaDePrueba"
}

###

POST {{BackEnd_HostAddress}}/api/auth/register/secure/admin
Content-Type: application/json
{
  "Email": "adminprueba@gmail.com",
  "NombreUsuario": "admin123",
  "Contrasena": "admin123",
  "NombreAdmin": "Juanito"
}
###

POST {{BackEnd_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "UsuUsernameOrEmail": "adminprueba@gmail.com",
  "UsuContrasena": "admin123"
}

###

GET {{BackEnd_HostAddress}}/api/productos/categoria=1
Accept: application/json

###

GET {{BackEnd_HostAddress}}/api/productos/estilo=2
Accept: application/json

###

GET {{BackEnd_HostAddress}}/api/admin/reportes/productos
Accept: application/json

###
GET {{BackEnd_HostAddress}}/api/admin/reportes/productos/44
Accept: application/json

###
POST {{BackEnd_HostAddress}}/api/admin/reportes/productos
Content-Type: application/json

{
  "ProNombre": "Camiseta Oversize Premium",
  "ProDescripcion": "Algodón pesado 240gr ideal para streetwear.",
  "ProGenero": "Unisex",
  "CatId": 2,
  "EstId": 1,
  "ProPrecio": 39.99,
  "ProDescuento": 10,
  "ProDescuentoInicio": "2026-06-01T00:00:00Z",
  "ProDescuentoFin": "2026-06-15T23:59:59Z"
}

###
PUT {{BackEnd_HostAddress}}/api/admin/reportes/productos/44
Content-Type: application/json

{
  "ProNombre": "Camiseta Oversize Premium (Editada)",
  "ProDescripcion": "Nueva descripción actualizada desde FastAPI.",
  "ProGenero": "Unisex",
  "CatId": 2,
  "EstId": 1,
  "ProPrecio": 35.00,
  "ProDescuento": null,
  "ProDescuentoInicio": null,
  "ProDescuentoFin": null
}

###
DELETE {{BackEnd_HostAddress}}/api/admin/reportes/productos/44
Accept: application/json

###

GET {{BackEnd_HostAddress}}/api/productos
Accept: application/json

###

GET {{BackEnd_HostAddress}}/api/productos?categoria=5&estilo=3&preciomax=37&preciomin=33
Accept: application/json

###

GET {{BackEnd_HostAddress}}/api/productos?categoria=5&categoria=4&stock=true
Accept: application/json

###

GET {{BackEnd_HostAddress}}/api/productos?categoria=1
###

GET {{BackEnd_HostAddress}}/api/productos/2
###

POST {{BackEnd_HostAddress}}/api/admin/reportes/categorias
Content-Type: application/json
{
  "CatNombre": "EsoOlil"
}
###
PUT {{BackEnd_HostAddress}}/api/admin/reportes/categorias/14
Content-Type: application/json
{
  "CatNombre": "EsoOASDASlil"
}
###
DELETE {{BackEnd_HostAddress}}/api/admin/reportes/categorias/14
Accept: application/json
###
###

POST {{BackEnd_HostAddress}}/api/admin/reportes/estilos
Content-Type: application/json
{
  "EstNombre": "EsoOlil"
}
###
PUT {{BackEnd_HostAddress}}/api/admin/reportes/estilos/5
Content-Type: application/json
{
  "EstNombre": "EsoOASDASlil"
}
###
DELETE {{BackEnd_HostAddress}}/api/admin/reportes/estilos/5
Accept: application/json
###

POST {{BackEnd_HostAddress}}/api/auth/login
Content-Type: application/json
{
  "UsuUsernameOrEmail": "emaildeprueba@gmail.com",
  "UsuContrasena": "contrasenaDePrueba"
}
###

GET {{BackEnd_Https}}/api/profile/mi-perfil
Accept: application/json
Authorization: Bearer {{mitoken}}
###

PUT {{BackEnd_Https}}/api/profile/mi-perfil
Authorization: Bearer {{mitoken}}
Content-Type: application/json
{
  "cliNombre": "Juan Gabriel",
  "cliApellido": "Garcia",
  "usuUsername": "emaildeprueba",
  "usuEmail": "emaildeprueba@gmail.com",
  "cliTelefono": null
}
###
GET {{BackEnd_Https}}/api/profile/direcciones
Accept: application/json
Authorization: Bearer {{mitoken}}
###

POST {{BackEnd_Https}}/api/profile/direcciones
Content-Type: application/json
Authorization: Bearer {{mitoken}}
{
  "DirCalle": "calle",
  "DirDistrito": "distrito",
  "DirProvincia": "provincia",
  "DirDepartamento": "departamento",
  "DirReferencia": "referencia",
  "DirPreferido": true
}
###
  
PUT {{BackEnd_Https}}/api/profile/direcciones/1
Content-Type: application/json
Authorization: Bearer {{mitoken}}
{
  "DirCalle": "calle2",
  "DirDistrito": "distrito",
  "DirProvincia": "provincia",
  "DirDepartamento": "departamento",
  "DirReferencia": "referencia",
  "DirPreferido": false
}
###
DELETE {{BackEnd_Https}}/api/profile/direcciones/1
Content-Type: application/json
Authorization: Bearer {{mitoken}}